apiVersion: apps/v1
kind: Deployment
metadata:
  name: catworld-deployment
  labels:
    app: catworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catworld
  template:
    metadata:
      labels:
        app: catworld
    spec:
      containers:
      - name: catworld
        image: yuwang55/catworld:0.3 
        ports:
        - containerPort: 8080
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
           secretKeyRef:
            name: mongo-secret
            key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
           secretKeyRef:
            name: mongo-secret
            key: mongo-password  
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
           configMapKeyRef:
            name: catworld-config
            key: mongo-service        
           
---
apiVersion: v1
kind: Service
metadata:
  name: catworld-service
spec:
  type: NodePort
  selector:
    app: catworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30020