version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
       - mongo-data:/data/db
  catworld:
    image: yuwang55/catworld:0.3
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo:27017
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
 
volumes:
    mongo-data:
       driver: local
       